insert into Department (Department_ID, DepartmentName, QuanEmployee) values (1, 'Services', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (2, 'Business Development', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (3, 'Research and Development', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (4, 'Services', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (5, 'Sales', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (6, 'Sales', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (7, 'Product Management', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (8, 'Training', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (9, 'Support', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (10, 'Business Development', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (11, 'Services', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (12, 'Support', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (13, 'Training', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (14, 'Marketing', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (15, 'Training', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (16, 'Human Resources', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (17, 'Accounting', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (18, 'Business Development', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (19, 'Training', 0);
insert into Department (Department_ID, DepartmentName, QuanEmployee) values (20, 'Human Resources', 0);